Slime blocks (bonemeal, honeyblock, seagrass)
String (wool block) or (3 wheat diagonal)
Spider eyes (bonemeal corners, slime center, string in gaps)
Rotten flesh (meat, slime, mushroom)
Ender pearls (slime surrounded by bonemeal)
Blaze rods (6 glowstone 3 sticks)
Gunpowder (magma block, two coal/charcoal, sand)
Ghast tears (gunpowder center, smooth quartz block corners, iron block gaps)
Phantom membranes (leather center, feather corner, slimeball gap)
Shulker shells (purple die center, bone block pants)
Nether stars (sea lantern middle, diamond block corners, echo shard gap)
Bones (from bone meal obtained from a composter) (diagnol bone meal)

Tridents (prismarine shaft, sea lantern forks)
Totems of Undying (ghast tear center bottom, emerald block right and left, rest gold block)
Sponges (water bucket center, fish corner, white wool bottom, green woold left and right, yellow wool up)
Dragon breath (potion bottle, two popped chorus, gunpowder)
Honeycomb (6 honey block, 3 bonemeal)
Rabbit Hide (honeycomb center, paper corner, string gap)
Honey Bottle (potion, two sugar, flower)
Feather (stick, two paper, string)
Froglights (all colors) (glowstone, gap phantom membran, corners one of glowstondust, emerald, amythyst)
